version: '3.9'

services:
  db-vm:
    build:
      context: ./db
      args:
        TOLMACHEV_HASH: ${TOLMACHEV_HASH}
    container_name: db-vm
    hostname: db-vm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: labdb
    networks:
      users_net:
        ipv4_address: 192.168.110.2

  admin-vm:
    build:
      context: ./admin
      args:
        TOLMACHEV_HASH: ${TOLMACHEV_HASH}
    container_name: admin-vm
    hostname: admin-vm
    depends_on:
      - db-vm
    networks:
      users_net:
        ipv4_address: 192.168.110.3

networks:
  users_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.110.0/24
